version: '3.8'

volumes:
  postgres_db_data:

services:
  backend: &backend
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app 
    command: flask run --host=0.0.0.0  --reload
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_db
    ports:
      - "5438:5432"

  celery_worker:
    <<: *backend
    ports: [ ]
    expose: [ ]
    command: celery -A survey.celery worker --loglevel=info
    depends_on:
      - db
      - backend
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"