"""add scheduled_time in survey

Revision ID: 360fbdd1dee4
Revises: 1e7bf484df16
Create Date: 2025-06-19 08:21:06.742903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360fbdd1dee4'
down_revision = '1e7bf484df16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
