"""add index for survey_id

Revision ID: 42fa6b72059c
Revises: 360fbdd1dee4
Create Date: 2025-06-20 12:23:03.597244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fa6b72059c'
down_revision = '360fbdd1dee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_survey_id'), ['survey_id'], unique=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_survey_id'), ['survey_id'], unique=False)

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_id'))

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_survey_id'))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_survey_id'))

    # ### end Alembic commands ###
